name: food_delivery
description: "Food delivery App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_bloc:
  flutter_screenutil: 
  flutter_svg:
  flutter_native_splash:
  flutter_platform_widgets:
  smooth_page_indicator:
  gap:
  auto_size_text: 
  device_preview:

dev_dependencies:
  flutter_lints: 
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 
  
flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  adaptive_icon_padding: false
  android: true 
  ios: true 
  remove_alpha_ios: false
  adaptive_icon_background: "#ffffff"



flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/
    - assets/images/splash.png
    - assets/images/logo.png

  
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700



  